-- Table: public.application_user

-- DROP TABLE public.application_user;

CREATE TABLE public.application_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    apellido character varying(255) COLLATE pg_catalog."default",
    dni character varying(255) COLLATE pg_catalog."default",
    mail character varying(255) COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    tipo_usuario integer,
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT application_user_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.application_user
    OWNER to postgres;

-- Table: public.spring_session

-- DROP TABLE public.spring_session;

CREATE TABLE public.spring_session
(
    primary_id character(36) COLLATE pg_catalog."default" NOT NULL,
    session_id character(36) COLLATE pg_catalog."default" NOT NULL,
    creation_time bigint NOT NULL,
    last_access_time bigint NOT NULL,
    max_inactive_interval integer NOT NULL,
    expiry_time bigint NOT NULL,
    principal_name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT spring_session_pk PRIMARY KEY (primary_id)
)

TABLESPACE pg_default;

ALTER TABLE public.spring_session
    OWNER to postgres;

-- Index: spring_session_ix1

-- DROP INDEX public.spring_session_ix1;

CREATE UNIQUE INDEX spring_session_ix1
    ON public.spring_session USING btree
    (session_id COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: spring_session_ix2

-- DROP INDEX public.spring_session_ix2;

CREATE INDEX spring_session_ix2
    ON public.spring_session USING btree
    (expiry_time ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: spring_session_ix3

-- DROP INDEX public.spring_session_ix3;

CREATE INDEX spring_session_ix3
    ON public.spring_session USING btree
    (principal_name COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
	
	
-- Table: public.spring_session_attributes

-- DROP TABLE public.spring_session_attributes;

CREATE TABLE public.spring_session_attributes
(
    session_primary_id character(36) COLLATE pg_catalog."default" NOT NULL,
    attribute_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    attribute_bytes bytea NOT NULL,
    CONSTRAINT spring_session_attributes_pk PRIMARY KEY (session_primary_id, attribute_name),
    CONSTRAINT spring_session_attributes_fk FOREIGN KEY (session_primary_id)
        REFERENCES public.spring_session (primary_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public.spring_session_attributes
    OWNER to postgres;

-- Table: public.tipo_licencia

-- DROP TABLE public.tipo_licencia;

CREATE TABLE public.tipo_licencia
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo integer,
    edad_maxima integer,
    edad_minima integer,
    licencia_profesional boolean,
    CONSTRAINT tipo_licencia_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.tipo_licencia
    OWNER to postgres;

-- Table: public.tipo_licencia_licencias_necesarias

-- DROP TABLE public.tipo_licencia_licencias_necesarias;

CREATE TABLE public.tipo_licencia_licencias_necesarias
(
    tipo_licencia_id bigint NOT NULL,
    licencias_necesarias_id bigint NOT NULL,
    CONSTRAINT constraint_foreignkey_primary FOREIGN KEY (tipo_licencia_id)
        REFERENCES public.tipo_licencia (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT constraint_foreignkey_dependent FOREIGN KEY (licencias_necesarias_id)
        REFERENCES public.tipo_licencia (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.tipo_licencia_licencias_necesarias
    OWNER to postgres;

-- Table: public.titular_licencia

-- DROP TABLE public.titular_licencia;

CREATE TABLE public.titular_licencia
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    apellido character varying(255) COLLATE pg_catalog."default",
    domicilio character varying(255) COLLATE pg_catalog."default",
    donante boolean,
    factor_rh integer,
    fecha_nacimiento date,
    foto character varying(255) COLLATE pg_catalog."default",
    grupo_sanguineo integer,
    nombre character varying(255) COLLATE pg_catalog."default",
    nro_documento character varying(255) COLLATE pg_catalog."default",
    tipo_documento integer,
    CONSTRAINT titular_licencia_pkey PRIMARY KEY (id),
    CONSTRAINT documento_unico UNIQUE (nro_documento, tipo_documento)
)

TABLESPACE pg_default;

ALTER TABLE public.titular_licencia
    OWNER to postgres;

-- Table: public.costo_licencia

-- DROP TABLE public.costo_licencia;

CREATE TABLE public.costo_licencia
(
    tipo integer NOT NULL,
    costo_administrativo integer,
    year1 integer,
    year3 integer,
    year4 integer,
    year5 integer,
    CONSTRAINT costo_licencia_pkey PRIMARY KEY (tipo)
)

TABLESPACE pg_default;

ALTER TABLE public.costo_licencia
    OWNER to postgres;

-- Table: public.vigencia

-- DROP TABLE public.vigencia;

CREATE TABLE public.vigencia
(
    rango_inferior_edad integer NOT NULL,
    rango_superior_edad integer NOT NULL,
    tiempo_vigencia integer,
    tiempo_vigencia_primera_vez integer,
    CONSTRAINT vigencia_pkey PRIMARY KEY (rango_inferior_edad, rango_superior_edad)
)

TABLESPACE pg_default;

ALTER TABLE public.vigencia
    OWNER to postgres;

-- Table: public.licencia

-- DROP TABLE public.licencia;

CREATE TABLE public.licencia
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    estado integer,
    fecha_fin_vigencia timestamp without time zone,
    fecha_inicio_vigencia timestamp without time zone,
    limitaciones character varying(255) COLLATE pg_catalog."default",
    numero_copia integer,
    observaciones character varying(255) COLLATE pg_catalog."default",
    tipo_licencia_id bigint,
    titular_id bigint,
    CONSTRAINT licencia_pkey PRIMARY KEY (id),
    CONSTRAINT fk9yydai3clv3o7t2mntsyc76lj FOREIGN KEY (tipo_licencia_id)
        REFERENCES public.tipo_licencia (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkiivjlhj14t682wn7kqsb39v70 FOREIGN KEY (titular_id)
        REFERENCES public.titular_licencia (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.licencia
    OWNER to postgres;
